server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/${notification_db_name}
    username: ${db_username}
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.bytebites.notificationservice.event,com.bytebites.orderservice.event,com.bytebites.restaurantservice.event"
        auto.offset.reset: earliest
        enable.auto.commit: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

bytebites:
  kafka:
    topics:
      order-events: order-events
      restaurant-events: restaurant-events

  email:
    enabled: false
    from: ""
