server:
  port: 8083

spring:

  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    username: mrlii
    password: postgresdev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

bytebites:
  services:
    restaurant:
      url: lb://restaurant-service
      timeout: 5000

  events:
    order:
      topic: order-events

management:
  endpoints:
    web:
      exposure:
        include: health,info